### ISSUE TITLE
Suggestion: Add InpureCore for NEI cleanup

### ISSUE THREAD

**Issue by Xavion3** [AlienMC/AlienMC-FTBSubreddit-Public-Server#1]
[InpureCore](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2196459-1-7-10-inpure-projects-denoflions-mods), it automatically cleans up NEI, removing things such as 20 pages of microblocks or 200 drums and leaving only a single copy behind so you can see the recipes.

**Comment by hadn69** [comment]
Added inPure Core
