### ISSUE TITLE
No way to sustainably create Mekanism Brine

### ISSUE THREAD

**Issue by Saereth** [AlienMC/AlienMC-FTBSubreddit-Public-Server#10]
Without mekanism generators there is no way to create brine for several Mekanism machines. With something like Pams you could make salt from water and setup a factory like that, doesnt seem to be an alternative in this pack. 

You can shapecraft 4 mekanism salt into a block and then macerate that for 9, but it produces gregtech salt which wont unify (even with a unifier) back to mekanism salt to shapecraft back into 4. Something like a mekanism enrichment recipe to turn 1 salt into 2 salt at the cost of rf/operation could work here.

**Comment by Shadows-of-Fire** [comment]
On it.

**Comment by Shadows-of-Fire** [comment]
Added Mek Gens.
