### ISSUE TITLE
Support for MFR BioReactor with AgriCraft seeds. 

### ISSUE THREAD

**Issue by zlepper** [AlienMC/AlienMC-FTBSubreddit-Public-Server#12]
Currently the MFR bioreactor does not support agricraft seeds, which doesn't really make sense, since they can be harvested by MFR. 
Supposedly this can be fixed by adding the seeds to the MFR planters supported seeds, as seen here: http://minetweaker3.powerofbytes.com/wiki/Mods:MFR_Support

**Comment by Shadows-of-Fire** [comment]
May do this, but since harvesting agricraft crops doesn't give out seeds it seems rather pointless. If its really that big of a problem just make a large 10/10/10 melon/pumpkin farm.

**Comment by Shadows-of-Fire** [comment]
Agricraft crops do not produce seeds. Will not be adding, unless someone else picks it up
