### ISSUE TITLE
cofh/world ore fluff

### ISSUE THREAD

**Issue by Thistlebalm** [AlienMC/AlienMC-FTBSubreddit-Public-Server#17]
There seems to be a bit of extra 'fluff' in cofh/world. 

'BluePower-Ores' with no blue power 

'ThermalExpansion-Ores' and 'ThermalFoundation-Ores' are exactly the same

'FTB-Infinity-Ores' already has Yellorite, Amethyst, Aluminium, and Certus Quartz, but you've got 'BigReactors-Ores', 'BoP', 'TConstruct-Ores', and 'AE2-Ores' with different values.

'FTB-Infinity-Ores' has Railcraft Sulfur, but the config/railcraft 'railcraft.cfg' still has sulfur generation enabled.

'FTB-Infinity-Ores' has Forestry Apatite, but the config/forestry 'common.conf' still has apatite generation enabled.

'Mekanism-Ores' only has Osmium, which isn't really a problem.

Any way just pointing it out :)

**Comment by hadn69** [comment]
I have fixed this in the 2.0.0 update.
