### ISSUE TITLE
Suggestion: Enable dimensional shard recipe

### ISSUE THREAD

**Issue by Xavion3** [AlienMC/AlienMC-FTBSubreddit-Public-Server#2]
As dimensions are disabled there is no way of obtaining these which are used with RF Tools machines, there is a config to enable a dimensional shard recipe, actually suggested for use with servers that disable dimensions.

**Comment by Shadows-of-Fire** [comment]
Shouldn't this issue be closed.

**Comment by Xavion3** [comment]
Not unless either the config is change https://github.com/AlienMC/AlienMC-FTBSubreddit-Public-Server/blob/master/config/rftools/main.cfg#L146, it's decided not to be changed, or dimensions are allowed now. No idea if any of those are true though.

**Comment by Shadows-of-Fire** [comment]
Player dims are allowed.

**Comment by Saereth** [comment]
additionally you can get these via villager trades
